---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=2.1.0.0
cache: bundler
#sudo: false
sudo: required
dist: trusty
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
#   - cmake
   - time
   - gcc-4.8
   - g++-4.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install dependencies.
  #- ansible-galaxy install alban.andrieu.cmake
  - git clone https://github.com/AlbanAndrieu/ansible-cmake.git alban.andrieu.cmake

script:
  - sudo ansible --version
  - export ANSIBLE_ROLES_PATH="../"
#  - echo localhost > inventory
  - ansible-playbook -i hosts --syntax-check cpp.yml
  - ansible-playbook -i hosts --connection=local --sudo -vvvv cpp.yml
