---
language: python
python: "2.7"
env:
#  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.9.7
cache: bundler
#sudo: false
sudo: required
dist: trusty
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
#   - cmake
   - time
   - gcc-4.8
   - g++-4.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install dependencies.
  #- ansible-galaxy install alban.andrieu.cmake
  #- git clone https://github.com/AlbanAndrieu/ansible-cmake.git alban.andrieu.cmake
  #- git clone https://github.com/AlbanAndrieu/ansible-scons.git alban.andrieu.scons
  #- git clone https://github.com/AlbanAndrieu/ansible-gcc.git alban.andrieu.gcc

script:
  # Check ansible version
  - ansible --version

  # Prepare tests
  #- echo localhost > hosts
  #- export ANSIBLE_ROLES_PATH="../"

  - ansible-galaxy install --role-file requirements.yml

  # Check syntax
  - ansible-playbook -i hosts --syntax-check cpp.yml

  # First run
  - ansible-playbook -i hosts --connection=local -vvvv cpp.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      - alban.andrieu@nabla.mobi
#      - other@example.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
